### ISSUE TITLE
Tag the 0.2.3 release

### ISSUE THREAD

**Issue by MatejLach** [xinranmsn/LangKit#2]
Hi, 
I would like to make use of this library, but currently it doesn't build since SPM relies on git tags and the latest tagged version, `0.2.2`, uses a `Package.swift`, which links to an outdated `CommandLine` dependency. 
The latest code at `master` fixes that, but SPM doesn't pull in the latest code since it is not tagged, it would therefore be useful to tag the current code at `master` as `0.2.3` so that it can be built again.

Thanks for working on this!

**Comment by xinranmsn** [comment]
Just added tag 0.2.3. Thanks for letting me know!
